/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as GalleryVaultIdRouteImport } from './routes/gallery.$vaultId'
import { Route as ScreeningMediaIdRouteImport } from './routes/screening.$mediaId'
import { Route as VaultVaultIdRouteImport } from './routes/vault.$vaultId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryVaultIdRoute = GalleryVaultIdRouteImport.update({
  id: '/gallery/$vaultId',
  path: '/gallery/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningMediaIdRoute = ScreeningMediaIdRouteImport.update({
  id: '/screening/$mediaId',
  path: '/screening/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultVaultIdRoute = VaultVaultIdRouteImport.update({
  id: '/vault/$vaultId',
  path: '/vault/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/gallery/$vaultId': typeof GalleryVaultIdRoute
  '/screening/$mediaId': typeof ScreeningMediaIdRoute
  '/vault/$vaultId': typeof VaultVaultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/gallery/$vaultId': typeof GalleryVaultIdRoute
  '/screening/$mediaId': typeof ScreeningMediaIdRoute
  '/vault/$vaultId': typeof VaultVaultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/gallery/$vaultId': typeof GalleryVaultIdRoute
  '/screening/$mediaId': typeof ScreeningMediaIdRoute
  '/vault/$vaultId': typeof VaultVaultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/gallery/$vaultId'
    | '/screening/$mediaId'
    | '/vault/$vaultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/gallery/$vaultId'
    | '/screening/$mediaId'
    | '/vault/$vaultId'
  id:
    | '__root__'
    | '/'
    | '/signup'
    | '/gallery/$vaultId'
    | '/screening/$mediaId'
    | '/vault/$vaultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignupRoute: typeof SignupRoute
  GalleryVaultIdRoute: typeof GalleryVaultIdRoute
  ScreeningMediaIdRoute: typeof ScreeningMediaIdRoute
  VaultVaultIdRoute: typeof VaultVaultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$vaultId': {
      id: '/gallery/$vaultId'
      path: '/gallery/$vaultId'
      fullPath: '/gallery/$vaultId'
      preLoaderRoute: typeof GalleryVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/$mediaId': {
      id: '/screening/$mediaId'
      path: '/screening/$mediaId'
      fullPath: '/screening/$mediaId'
      preLoaderRoute: typeof ScreeningMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$vaultId': {
      id: '/vault/$vaultId'
      path: '/vault/$vaultId'
      fullPath: '/vault/$vaultId'
      preLoaderRoute: typeof VaultVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignupRoute: SignupRoute,
  GalleryVaultIdRoute: GalleryVaultIdRoute,
  ScreeningMediaIdRoute: ScreeningMediaIdRoute,
  VaultVaultIdRoute: VaultVaultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
